# Generated by Django 3.2 on 2021-04-11 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.IntegerField()),
                ('partiallySolved', models.IntegerField()),
                ('attemped', models.IntegerField()),
                ('score', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('problemsSolved', models.TextField(blank=True, null=True)),
                ('problemPartiallySolved', models.TextField(blank=True, null=True)),
                ('dateTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datetime')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('userName', models.TextField()),
                ('eMail', models.EmailField(max_length=254)),
                ('passWord', models.TextField()),
                ('userDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.historymodel')),
            ],
        ),
    ]
