# Generated by Django 3.2 on 2021-04-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historymodel',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='historymodel',
            name='dateTime',
            field=models.ManyToManyField(to='api.DateTime'),
        ),
    ]
