# Generated by Django 3.2 on 2021-04-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210411_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='dateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
